### ISSUE TITLE
Transient identities and traits feature introduced a breaking change

### ISSUE THREAD

**Issue by JSkimming** [Flagsmith/flagsmith-dotnet-client#120]
The PR #111, to add Transient identities and traits, introduced a breaking change to the API.

It appears you follow semantic versioning, and if so, this should have warranted a major version bump.

The breaking change was to add the parameter `transient` with a default value of `false` to several methods. While this may seem like a non-breaking change because it has a default value, default values are handled at compile time, meaning a recompile, at the very minimum, is required to be compatible.

If a third-party library were to be published via NuGet that used one of these APIs, then it would result in a runtime-only error due to a missing method, that missing method being the one before the addition of the new `transient` parameter.

The impact on ourselves is negligible. We had to make a few small changes to our tests (see the compile error below) as mocks no longer compiled. Moq uses expression trees, which do not support optional parameters.

```
error CS0854: An expression tree may not contain a call or invocation that uses optional arguments
```

I'm not suggesting you publish a fix or a version bump update (others may disagree). I'm writing this to highlight the issue, and if you are trying to adhere to semantic versioning, this should be avoided in future.

**Comment by matthewelwell** [comment]
Hi @JSkimming , thanks for all the detailed information and apologies for the issues that you experienced. 

I wasn't aware that adding new optional arguments to a method was a breaking change under these circumstances, so thank you for pointing this out. We will for sure keep this in mind for future. 

I suppose that, in future, to add a non-breaking change, we should instead use overloads, and not add optional arguments to existing methods. 

Let me know if there's anything else you want to add or ask, otherwise, I'll go ahead and close this issue and keep it in mind for future changes.

**Comment by JSkimming** [comment]
Hi @matthewelwell. Yes, method overloads are the route to go to maintain backwards compatibility. Please do close the issue.
