### ISSUE TITLE
FlagsmithClient's interface was completely changed

### ISSUE THREAD

**Issue by svetak-quali** [Flagsmith/flagsmith-dotnet-client#41]
Hi,

We were using Flagsmith 3.1.0 nuget package and thought to upgrade and it seems that all the interface has changed...
Was the 3.1.0 a beta release? What are the plans with the future releases? Are there any breaking changes expected there?
We see that there is no SetTraits method in the new interface. So how do we add users and traits dynamically in the new version?

Thanks,
Sveta

**Comment by matthewelwell** [comment]
Hi @svetak-quali,

Yes, the interface in v4.0.0 was completely overhauled to give a consistent interface between all of our server side clients. We released this as a major version update to limit the impact to existing customers. We also added a major improvement by allowing users to configure local evaluation so I would definitely recommend upgrading if you have the capacity. 

In order to set traits in the new clients, you just need to call `FlagsmithClient.GetIdentityFlags()` with an identifier and a list of `Trait` objects. This will retrieve the flags for an identity as well as setting the traits on the identity. 

You can read more about the new SDK [here](https://docs.flagsmith.com/clients/server-side).

**Comment by svetak-quali** [comment]
Thanks. We will look into a new SDK
